version: 2
updates:
  - package-ecosystem: "gomod"
    # Setting the limit to zero should limit
    # Dependabot to security updates only.
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
      include: "scope"